# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2b54ff57b08db86ee535148282b1ffdeae4d33611585e69024b6dfbaca887f7163d8c9fcdea81c0a7f9837b19bc72db140f8d369cdc5083a35bd3bfa97e28388

test:
  secret_key_base: c1fb731d588371d7880b72062ac74ceeeca2501decddf8fec1c5f64f78990d752b8ef3473547346cb6e0105c7850cf88429aeeb0820f28c1b3cfc81ce87e11a3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
